version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "5007:80"

  backend:
    build: ./backend
    ports:
      - "5008:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/iotdata
    depends_on:
      - mongo

  mqtt-client:
    build: ./backend
    command: node mqtt-client.js
    environment:
      - MONGO_URL=mongodb://mongo:27017/iotdata
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27020:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: